#!/usr/bin/env ruby
# Author:: Adam Jacob (<adam@hjksolutions.com>)
# Copyright:: Copyright (c) 2008 iLike Inc. and HJK Solutions, LLC
# License:: GNU General Public License version 2 or later
# 
# This program and entire repository is free software; you can
# redistribute it and/or modify it under the terms of the GNU 
# General Public License as published by the Free Software 
# Foundation; either version 2 of the License, or any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
# 

require 'AdduserLDAP'

arguments = ARGV

default_file = nil

if File.exist?(arguments[0])
  default_file = arguments.shift
elsif File.exist?(File.join("etc", "adduser-ldap", "config.yml"))
  default_file = "/etc/adduser-ldap/config.yml"
end if arguments.length > 0

cli = AdduserLDAP::CLI.new(default_file, arguments)
cli.adduser

exit 0
