server: admin.example.com
port: 389
ssl: true
starttls: true
basedn: ou=people,dc=example,dc=com
groupdn: ou=Groups,dc=example,dc=com
rdn: uid
uidnumber_filter: '(uidNumber=*)'
gidnumber_default: 301
loginshell_default: /bin/bash
homedir_base: /home
